# Application
spring.application.name=demo

# Oracle DB connection
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=keerthan0407
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA configuration
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Server
server.port=8080
